# Generated by Django 3.2.16 on 2022-10-28 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='post_image',
        ),
    ]
