# Generated by Django 3.2.16 on 2022-10-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0003_alter_postmodel_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='comment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='likemodel',
            name='like_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
